Cert: "cert"
Peers: "peerList"
PortNbr: "portNbr"
NodeBackupFileName: "nodeBackup.json"
NodeBackupPath: "nodeBackupPath"
Version: "v0.0.6-alpha"
DefaultRPCURL: "https://ethereum-sepolia.publicnode.com"
Environment: "dev"
