version: '3.8'
services:
  masa-node:
    build: .
    ports:
      - "4001:4001"
      - "8080:8080"
    environment:
      BOOTNODES: "/ip4/35.223.224.220/udp/4001/quic-v1/p2p/16Uiu2HAmPxXXjR1XJEwckh6q1UStheMmGaGe8fyXdeRs3SejadSa"
      RPC_URL: "https://sepolia.infura.io/v3/74533a2e74bc430188366f3aa5715ae1"
    volumes:
      - .:/app
      - .masa-keys:/home/masa/.masa

volumes:
  masa-keys:
    # This is a named volume. You can specify additional options here if needed,
    # such as setting a specific driver, driver options, or even labeling.
    # For most users, the simple declaration is sufficient.
    # Example with explicit driver (usually not required):
    # driver: local
    # Example with labels (optional):
    # labels:
    #   - "com.example.description=MASA node key storage"

