apiVersion: v1
kind: Service
metadata:
  name: masa-oracle-test
  labels:
    helm.sh/chart: masa-oracle-0.1.0
    app.kubernetes.io/name: masa-oracle
    app.kubernetes.io/instance: masa-oracle-test
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: LoadBalancer
  ports:
    - port: 4001
      targetPort: 4001
      protocol: UDP
      name: UDPconnection
  selector:
    app.kubernetes.io/name: masa-oracle
    app.kubernetes.io/instance: masa-oracle-test
