apiVersion: v1
kind: Service
metadata:
  name: {{ include "masa-oracle.fullname" . }}
  labels:
    {{- include "masa-oracle.labels" . | nindent 4 }}
spec:
  externalTrafficPolicy: Local
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: UDP
      name: udpconnection
  selector:
    {{- include "masa-oracle.selectorLabels" . | nindent 4 }}
