apiVersion: v1
kind: Service
metadata:
  name: {{ include "masa-oracle.fullname" . }}
  labels:
    {{- include "masa-oracle.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: 4001
      targetPort: 4001
      protocol: TCP
      name: tcpconnection
  selector:
    {{- include "masa-oracle.selectorLabels" . | nindent 4 }}
