apiVersion: v1
kind: Service
metadata:
  name: {{ include "masa-oracle.fullname" . }}
  labels:
    {{- include "masa-oracle.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: Local
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: tcpconnection
  selector:
    {{- include "masa-oracle.selectorLabels" . | nindent 4 }}
