apiVersion: v1
kind: Service
metadata:
  name: {{ include "masa-oracle.fullname" . }}
  labels:
    {{- include "masa-oracle.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 4001
      targetPort: 4001
      protocol: UDP
      name: UDPconnection
  selector:
    {{- include "masa-oracle.selectorLabels" . | nindent 4 }}
