basePath: /api/v1
info:
  contact:
    email: support@masa.ai
    name: Masa API Support
    url: https://api.masa.ai
  license:
    name: MIT
    url: https://opensource.org/license/mit
paths: {}
swagger: "2.0"
