name: Build and run

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ["masa-oracle-1"]
    outputs:
      CONNECTION_STRING: ${{steps.host-selector.outputs.CONNECTION_STRING}}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Copy binary & restart service
      run: |
        sudo systemctl stop masa-oracle.service
        go mod tidy
        go build -v -o masa-node ./cmd/masa-node
        sudo cp -R . /home/mykhaylo/masa-oracle-main/
        sudo systemctl daemon-reload
        sudo systemctl restart masa-oracle.service
    - name: Get host address
      id: host-selector
      run: |
        CONNECTION_STRING=$(cat /var/log/masa-oracle/log1.log | grep 'Starting node with ID:' | awk '{print $NF}' | sed 's/"$//')
        while [ -z "$CONNECTION_STRING" ]
          do
            CONNECTION_STRING=$(cat /var/log/masa-oracle/log1.log | grep 'Starting node with ID:' | awk '{print $NF}' | sed 's/"$//')
          done
        echo $CONNECTION_STRING
        echo "CONNECTION_STRING=$CONNECTION_STRING" >> "$GITHUB_OUTPUT"
        
  connect:
    needs: deploy
    runs-on: ["masa-oracle-2"]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Fetch dependencies & build app
      run: |
        go mod tidy
        go build -v -o masa-node ./cmd/masa-node
        sudo cp -R . /home/mykhaylo/masa-oracle-main/
    - name: Copy binary & restart service
      run: |
        sudo systemctl stop masa-oracle.service
        echo "CONNECTION_STRING=${{needs.deploy.outputs.CONNECTION_STRING}}" > /home/mykhaylo/masa-oracle-main/cmd/masa-node/.argconf
        sudo systemctl daemon-reload
        sudo systemctl start masa-oracle.service
