name: Build and deploy (inputs)

on:
  workflow_dispatch:
    inputs:
      node1:
        description: "Bootnodes parameter for node 1"
        default: 'default'
        type: string
        required: true
      node2:
        description: "Bootnodes parameter for node 2"
        default: 'default'
        type: string
        required: true

jobs:
  deploy:
    runs-on: ["masa-oracle-node-1"]
    outputs:
      CONNECTION_STRING: ${{steps.host-selector.outputs.CONNECTION_STRING}}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Copy binary & restart service
      run: |
        echo "node1: ${{ inputs.node1 }}"
        /usr/local/go/bin/go mod tidy
        /usr/local/go/bin/go build -v -o masa-node ./cmd/masa-node
        export BOOTNODES="${{ inputs.node1 }}"
        if [[ "$BOOTNODES" == "default" ]]; then
          export BOOTNODES_ARG=""
          export BOOTNODES=""
        else
          export BOOTNODES_ARG="--bootnodes=";
        fi
        echo "ARG: $BOOTNODES_ARG NODES: $BOOTNODES"
        sudo cp -R . /home/masa/masa-oracle/
        cat system-service/masa-oracle.service | envsubst > masa-oracle.service
        sudo mv masa-oracle.service /etc/systemd/system/masa-oracle.service
        sudo systemctl daemon-reload
        sudo systemctl restart masa-oracle.service

    - name: Get host address
      id: host-selector
      run: |
        CONNECTION_STRING=$(cat /var/log/masa-oracle/logs.log | grep 'Starting node with ID:' | awk '{print $NF}' | sed 's/"$//')
        while [ -z "$CONNECTION_STRING" ]
          do
            CONNECTION_STRING=$(cat /var/log/masa-oracle/logs.log | grep 'Starting node with ID:' | awk '{print $NF}' | sed 's/"$//')
          done
        echo $CONNECTION_STRING
        echo "CONNECTION_STRING=$CONNECTION_STRING" >> "$GITHUB_OUTPUT"
        
  connect:
    needs: deploy
    runs-on: ["masa-oracle-node-2"]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Copy binary & restart service
      run: |
        /usr/local/go/bin/go mod tidy
        /usr/local/go/bin/go build -v -o masa-node ./cmd/masa-node
        export BOOTNODES='${{ inputs.node2 }}'
        export BOOTNODES_ARG="--bootnodes=";
        if [[ "$BOOTNODES" == "default" ]]; then
          export BOOTNODES="${{needs.deploy.outputs.CONNECTION_STRING}}"
        fi
        echo "ARG: $BOOTNODES_ARG NODES: $BOOTNODES"
        sudo cp -R . /home/masa/masa-oracle/
        cat system-service/masa-oracle.service | envsubst > masa-oracle.service
        sudo mv masa-oracle.service /etc/systemd/system/masa-oracle.service
        sudo systemctl daemon-reload
        sudo systemctl restart masa-oracle.service
