name: Build

on:
  pull_request:
    branches:
      - dev
      - test
      - stage
      - prod

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'main' || github.ref == 'refs/heads/test' && 'test' || 'dev' }}
    outputs:
      environment: ${{ steps.set-env.outputs.environment }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build Binary
        run: go build -v -o masa-node ./cmd/masa-node
