name: masa-oracle nodes deployment

on:
  workflow_dispatch:
    inputs:

      node1argbootnode:
        description: "Bootnodes parameter for node1"
        default: /ip4/137.66.11.250/udp/4001/quic-v1/p2p/16Uiu2HAmJtYy4A8pzChDQQLrPsu1SQU5apzCftCVaAjFk539CLc9,/ip4/168.220.95.86/udp/4001/quic-v1/p2p/16Uiu2HAmAb5Wac73G2QSQQfarhw95KveAaEUNX6yTXXpmmTtVmNW
        type: string
        required: true
      node1argextra:
        description: "Extra args except of --port, --udp, --tcp"
        default: 'default'
        type: string
        required: false 

      node2argbootnode:
        description: "Bootnodes parameter for node2"
        default: /ip4/137.66.11.250/udp/4001/quic-v1/p2p/16Uiu2HAmJtYy4A8pzChDQQLrPsu1SQU5apzCftCVaAjFk539CLc9,/ip4/168.220.95.86/udp/4001/quic-v1/p2p/16Uiu2HAmAb5Wac73G2QSQQfarhw95KveAaEUNX6yTXXpmmTtVmNW
        type: string
        required: true
      node2argextra:
        description: "Extra args except of --port, --udp, --tcp"
        default: 'default'
        type: string
        required: false 

      node3argbootnode:
        description: "Bootnodes parameter for node3"
        default: 'default'
        type: string
        required: true
      node3argextra:
        description: "Extra args except of --port, --udp, --tcp"
        default: 'default'
        type: string
        required: false


jobs: 
  master-node3:
    runs-on: ["node3"]
    outputs:
      MASA_NODE_MULTIADDRESS: ${{steps.step2.outputs.MASA_NODE_MULTIADDRESS}}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Copy binary & restart service
      id: step2
      run: |
        echo "node3argbootnode: ${{ inputs.node3argbootnode }}"
        echo "node3argextra: ${{ inputs.node3argextra }}"
        /usr/local/go/bin/go mod tidy
        /usr/local/go/bin/go build -v -o masa-node ./cmd/masa-node
        export BOOTNODES="${{ inputs.node3argbootnode }}"
        export EXTRA_ARGS="${{ inputs.node3argextra }}"
        if [[ "$BOOTNODES" == "default" ]]; then
          export BOOTNODES_ARG=""
          export BOOTNODES=""
        else
          export BOOTNODES_ARG="--bootnodes=";
        fi
        echo "ARG: $BOOTNODES_ARG NODES: $BOOTNODES"
        rm -rf /home/masa/masa-oracle
        mkdir /home/masa/masa-oracle
        cp -R . /home/masa/masa-oracle/
        cat system-service/masa-oracle.service | envsubst > masa-oracle.service
        sudo mv masa-oracle.service /etc/systemd/system/masa-oracle.service
        sudo systemctl daemon-reload
        sudo systemctl restart masa-oracle.service    
        until [ -f /home/masa/.masa/masa_oracle_node_output.env ]; do sleep 5; done 
        source /home/masa/.masa/masa_oracle_node_output.env
        echo "MASA_NODE_MULTIADDRESS: $MASA_NODE_MULTIADDRESS"
        echo "MASA_NODE_MULTIADDRESS=$MASA_NODE_MULTIADDRESS" >> "$GITHUB_OUTPUT"


  joined_node1:
    runs-on: ["node1"]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Copy binary & restart service
      run: |
        echo "node1argbootnode: ${{ inputs.node1argbootnode }}"
        echo "node1argextra: ${{ inputs.node1argextra }}"
        /usr/local/go/bin/go mod tidy
        /usr/local/go/bin/go build -v -o masa-node ./cmd/masa-node
        export BOOTNODES="${{ inputs.node1argbootnode }}"
        export EXTRA_ARGS="${{ inputs.node1argextra }}"
        export BOOTNODES_ARG="--bootnodes=";
        if [[ "$$BOOTNODES" == "default" ]]; then
          export BOOTNODES=""
        fi
        echo "ARG: $BOOTNODES_ARG NODES: $BOOTNODES"
        rm -rf /home/masa/masa-oracle
        mkdir /home/masa/masa-oracle
        cp -R . /home/masa/masa-oracle/
        cat system-service/masa-oracle.service | envsubst > masa-oracle.service
        sudo mv masa-oracle.service /etc/systemd/system/masa-oracle.service
        sudo systemctl daemon-reload
        sudo systemctl restart masa-oracle.service
        until [ -f /home/masa/.masa/masa_oracle_node_output.env ]; do sleep 5; done 
        source /home/masa/.masa/masa_oracle_node_output.env
        echo "MASA_NODE_MULTIADDRESS: $MASA_NODE_MULTIADDRESS"
  joined_node2:
    runs-on: ["node2"]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Copy binary & restart service
      run: |
        echo "node2argbootnode: ${{ inputs.node2argbootnode }}"
        echo "node2argextra: ${{ inputs.node2argextra }}"
        /usr/local/go/bin/go mod tidy
        /usr/local/go/bin/go build -v -o masa-node ./cmd/masa-node
        export BOOTNODES="${{ inputs.node2argbootnode }}"
        export EXTRA_ARGS="${{ inputs.node2argextra }}"
        export BOOTNODES_ARG="--bootnodes=";
        if [[ "$$BOOTNODES" == "default" ]]; then
          export BOOTNODES=""
        fi
        echo "ARG: $BOOTNODES_ARG NODES: $BOOTNODES"
        rm -rf /home/masa/masa-oracle
        mkdir /home/masa/masa-oracle
        cp -R . /home/masa/masa-oracle/
        cat system-service/masa-oracle.service | envsubst > masa-oracle.service
        sudo mv masa-oracle.service /etc/systemd/system/masa-oracle.service
        sudo systemctl daemon-reload
        sudo systemctl restart masa-oracle.service
        until [ -f /home/masa/.masa/masa_oracle_node_output.env ]; do sleep 5; done 
        source /home/masa/.masa/masa_oracle_node_output.env
        echo "MASA_NODE_MULTIADDRESS: $MASA_NODE_MULTIADDRESS"
