name: masa-oracle nodes deployment

on:
  workflow_dispatch:
    inputs:

      node1argbootnode:
        description: "Bootnodes parameter for node1"
        default: /ip4/35.224.231.145/udp/4001/quic-v1/p2p/16Uiu2HAm47nBiewWLLzCREtY8vwPQtr5jTqyrEoUo6WnngwhsQuR,/ip4/104.198.43.138/udp/4001/quic-v1/p2p/16Uiu2HAkxiP8jjdHQWeCxTr7pD6BvoPkS8Z1skjCy9vdSRMACDcc
        type: string
        required: true
      node1argextra:
        description: "Extra args except of --port, --udp, --tcp"
        default: '--start=true'
        type: string
        required: false 

      node2argbootnode:
        description: "Bootnodes parameter for node2"
        default: /ip4/35.224.231.145/udp/4001/quic-v1/p2p/16Uiu2HAm47nBiewWLLzCREtY8vwPQtr5jTqyrEoUo6WnngwhsQuR,/ip4/104.198.43.138/udp/4001/quic-v1/p2p/16Uiu2HAkxiP8jjdHQWeCxTr7pD6BvoPkS8Z1skjCy9vdSRMACDcc
        type: string
        required: true
      node2argextra:
        description: "Extra args except of --port, --udp, --tcp"
        default: '--start=true'
        type: string
        required: false 

      node3argbootnode:
        description: "Bootnodes parameter for node3"
        default: /ip4/35.224.231.145/udp/4001/quic-v1/p2p/16Uiu2HAm47nBiewWLLzCREtY8vwPQtr5jTqyrEoUo6WnngwhsQuR,/ip4/104.198.43.138/udp/4001/quic-v1/p2p/16Uiu2HAkxiP8jjdHQWeCxTr7pD6BvoPkS8Z1skjCy9vdSRMACDcc
        type: string
        required: true
      node3argextra:
        description: "Extra args except of --port, --udp, --tcp"
        default: '--start=true'
        type: string
        required: false 

      node4argbootnode:
        description: "Bootnodes parameter for node4"
        default: /ip4/35.224.231.145/udp/4001/quic-v1/p2p/16Uiu2HAm47nBiewWLLzCREtY8vwPQtr5jTqyrEoUo6WnngwhsQuR,/ip4/104.198.43.138/udp/4001/quic-v1/p2p/16Uiu2HAkxiP8jjdHQWeCxTr7pD6BvoPkS8Z1skjCy9vdSRMACDcc
        type: string
        required: true
      node4argextra:
        description: "Extra args except of --port, --udp, --tcp"
        default: '--start=true'
        type: string
        required: false 

      node5argbootnode:
        description: "Bootnodes parameter for node5"
        default: /ip4/35.224.231.145/udp/4001/quic-v1/p2p/16Uiu2HAm47nBiewWLLzCREtY8vwPQtr5jTqyrEoUo6WnngwhsQuR,/ip4/104.198.43.138/udp/4001/quic-v1/p2p/16Uiu2HAkxiP8jjdHQWeCxTr7pD6BvoPkS8Z1skjCy9vdSRMACDcc
        type: string
        required: true
      node5argextra:
        description: "Extra args except of --port, --udp, --tcp"
        default: '--start=true'
        type: string
        required: false 

jobs: 
  joined_node1:
    runs-on: ["node1"]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Copy binary & restart service
      run: |
        echo "node1argbootnode: ${{ inputs.node1argbootnode }}"
        echo "node1argextra: ${{ inputs.node1argextra }}"
        /usr/local/go/bin/go mod tidy
        /usr/local/go/bin/go build -v -o masa-node ./cmd/masa-node
        export BOOTNODES="${{ inputs.node1argbootnode }}"
        export EXTRA_ARGS="${{ inputs.node1argextra }}"
        export BOOTNODES_ARG="--bootnodes=";
        if [[ "$$BOOTNODES" == "default" ]]; then
          export BOOTNODES=""
        fi
        echo "ARG: $BOOTNODES_ARG NODES: $BOOTNODES"
        sudo rm -rf /home/masa/masa-oracle
        mkdir /home/masa/masa-oracle
        cp -R . /home/masa/masa-oracle/
        cat system-service/masa-oracle.service | envsubst > masa-oracle.service
        echo "Debug service 3"
        cat masa-oracle.service
        sudo mv masa-oracle.service /etc/systemd/system/masa-oracle.service
        sudo systemctl daemon-reload
        sudo systemctl restart masa-oracle.service
        until [ -f /home/masa/.masa/masa_oracle_node_output.env ]; do sleep 5; done 
        source /home/masa/.masa/masa_oracle_node_output.env
        echo "MASA_NODE_MULTIADDRESS: $MASA_NODE_MULTIADDRESS"
  joined_node2:
    runs-on: ["node2"]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Copy binary & restart service
      run: |
        echo "node2argbootnode: ${{ inputs.node2argbootnode }}"
        echo "node2argextra: ${{ inputs.node2argextra }}"
        /usr/local/go/bin/go mod tidy
        /usr/local/go/bin/go build -v -o masa-node ./cmd/masa-node
        export BOOTNODES="${{ inputs.node2argbootnode }}"
        export EXTRA_ARGS="${{ inputs.node2argextra }}"
        export BOOTNODES_ARG="--bootnodes=";
        if [[ "$$BOOTNODES" == "default" ]]; then
          export BOOTNODES=""
        fi
        echo "ARG: $BOOTNODES_ARG NODES: $BOOTNODES"
        sudo rm -rf /home/masa/masa-oracle
        mkdir /home/masa/masa-oracle
        cp -R . /home/masa/masa-oracle/
        cat system-service/masa-oracle.service | envsubst > masa-oracle.service
        echo "Debug service 3"
        cat masa-oracle.service
        sudo mv masa-oracle.service /etc/systemd/system/masa-oracle.service
        sudo systemctl daemon-reload
        sudo systemctl restart masa-oracle.service
        until [ -f /home/masa/.masa/masa_oracle_node_output.env ]; do sleep 5; done 
        source /home/masa/.masa/masa_oracle_node_output.env
        echo "MASA_NODE_MULTIADDRESS: $MASA_NODE_MULTIADDRESS"
  joined_node3:
    runs-on: ["node3"]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Copy binary & restart service
      run: |
        echo "node3argbootnode: ${{ inputs.node3argbootnode }}"
        echo "node3argextra: ${{ inputs.node3argextra }}"
        /usr/local/go/bin/go mod tidy
        /usr/local/go/bin/go build -v -o masa-node ./cmd/masa-node
        export BOOTNODES="${{ inputs.node3argbootnode }}"
        export EXTRA_ARGS="${{ inputs.node3argextra }}"
        export BOOTNODES_ARG="--bootnodes=";
        if [[ "$$BOOTNODES" == "default" ]]; then
          export BOOTNODES=""
        fi
        echo "ARG: $BOOTNODES_ARG NODES: $BOOTNODES"
        sudo rm -rf /home/masa/masa-oracle
        mkdir /home/masa/masa-oracle
        cp -R . /home/masa/masa-oracle/
        cat system-service/masa-oracle.service | envsubst > masa-oracle.service
        echo "Debug service 3"
        cat masa-oracle.service
        sudo mv masa-oracle.service /etc/systemd/system/masa-oracle.service
        sudo systemctl daemon-reload
        sudo systemctl restart masa-oracle.service
        until [ -f /home/masa/.masa/masa_oracle_node_output.env ]; do sleep 5; done 
        source /home/masa/.masa/masa_oracle_node_output.env
        echo "MASA_NODE_MULTIADDRESS: $MASA_NODE_MULTIADDRESS"
  joined_node4:
    runs-on: ["node4"]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Copy binary & restart service
      run: |
        echo "node4argbootnode: ${{ inputs.node4argbootnode }}"
        echo "node4argextra: ${{ inputs.node4argextra }}"
        /usr/local/go/bin/go mod tidy
        /usr/local/go/bin/go build -v -o masa-node ./cmd/masa-node
        export BOOTNODES="${{ inputs.node4argbootnode }}"
        export EXTRA_ARGS="${{ inputs.node4argextra }}"
        export BOOTNODES_ARG="--bootnodes=";
        if [[ "$$BOOTNODES" == "default" ]]; then
          export BOOTNODES=""
        fi
        echo "ARG: $BOOTNODES_ARG NODES: $BOOTNODES"
        sudo rm -rf /home/masa/masa-oracle
        mkdir /home/masa/masa-oracle
        cp -R . /home/masa/masa-oracle/
        cat system-service/masa-oracle.service | envsubst > masa-oracle.service
        echo "Debug service 3"
        cat masa-oracle.service
        sudo mv masa-oracle.service /etc/systemd/system/masa-oracle.service
        sudo systemctl daemon-reload
        sudo systemctl restart masa-oracle.service
        until [ -f /home/masa/.masa/masa_oracle_node_output.env ]; do sleep 5; done 
        source /home/masa/.masa/masa_oracle_node_output.env
        echo "MASA_NODE_MULTIADDRESS: $MASA_NODE_MULTIADDRESS"
