name: release

on:
  push:
    branches:
      - main
      - test
      - dev

permissions:
  id-token: write
  contents: read

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract_version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from constants.go
        id: extract_version
        run: |
          VERSION=$(grep 'Version     = ' ./pkg/config/constants.go | awk '{print $NF}' | tr -d '"')
          echo "Extracted version: $VERSION"
          echo "::set-output name=version::$VERSION"

  release:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.prepare.outputs.version }}
          release_name: Release ${{ needs.prepare.outputs.version }}
          draft: false
          prerelease: false
          body: |
            # What's Changed 🌟
            # Changelog 🛠️
            * Feature 1 Test
            * Feature 2 Test
            * Fixed bugs a, b, c

            # Release Guide 🚀
            Lorem ipsum ...

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/masa-node
          asset_name: masa-node
          asset_content_type: application/octet
  
  build-and-release:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ github.ref == 'refs/heads/main' && 'main' || github.ref == 'refs/heads/test' && 'test' || 'dev' }}
    outputs:
      environment: ${{ steps.set-env.outputs.environment }}
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Build Binary
      run: go build -v -o masa-node ./cmd/masa-node
    
    - id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: projects/784882329213/locations/global/workloadIdentityPools/github-oidc-pool/providers/github-oidc-provider
        service_account: gh-masa-oracle-${{ github.ref_name }}@masa-chain.iam.gserviceaccount.com

    - name: Install Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: 'latest'
        project_id: ${{ vars.GCP_PROJECT_ID }}

    - name: Upload Binary and config for contracts npm modules to GCP
      run: |
        BINARY_NAME=$(git rev-parse --short HEAD)
        gsutil cp ./masa-node gs://${{ vars.GCP_BUCKET_NAME }}/$BINARY_NAME/masa-node
        gsutil cp ./masa-node gs://${{ vars.GCP_BUCKET_NAME }}/masa-node
        gsutil cp ./contracts/* gs://${{ vars.GCP_BUCKET_NAME }}/$BINARY_NAME/
        gsutil cp ./contracts/* gs://${{ vars.GCP_BUCKET_NAME }}/

    - name: Set environment output
      id: set-env
      run: echo "::set-output name=environment::${{ github.ref_name }}"

  deploy:
    needs: build-and-release
    runs-on: ubuntu-latest
    environment:
      name: ${{ needs.build-and-release.outputs.environment }}
    steps:
    - id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: projects/784882329213/locations/global/workloadIdentityPools/github-oidc-pool/providers/github-oidc-provider
        service_account: gh-masa-oracle-${{ github.ref_name }}@masa-chain.iam.gserviceaccount.com

    - name: Update Instance Metadata
      run: |
        ENVIRONMENT="${{ github.ref_name }}"
        echo "Looking for instances with env metadata: $ENVIRONMENT"
        INSTANCES=$(gcloud compute instances list --filter="metadata.items.ENV=$ENVIRONMENT" --format="get(name)")

        echo "Found instances: $INSTANCES"

        for INSTANCE in $INSTANCES; do
          ZONE=$(gcloud compute instances list --filter="name=($INSTANCE)" --format="get(zone)" --limit=1)
          echo "Updating instance: $INSTANCE in zone: $ZONE"
          gcloud compute instances add-metadata $INSTANCE --metadata masa-oracle-redeploy=latest --zone=$(echo $ZONE | tr -d '\n')
        done

