name: Release masa-oracle binary

on:
  push:
    branches:
      - dev
      - test
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21' 

    - name: Build Binary
      run: go build -v -o masa-node ./cmd/masa-node

    - name: Install Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        export_default_credentials: true

    - name: Upload Binary to GCP
      run: |
        BINARY_NAME=$(git rev-parse --short HEAD)
        gsutil cp ./masa-node gs://${{ secrets.GCP_BUCKET_NAME }}/${GITHUB_REF_NAME}/$BINARY_NAME

