name: release binary

on:
  push:
    branches:
      - main
      - test
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ github.ref == 'refs/heads/main' && 'main' || github.ref == 'refs/heads/test' && 'test' || 'dev' }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Cache Go Modules
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Build Binary
      run: go build -v -o masa-node ./cmd/masa-node

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Install Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: 'latest'
        project_id: ${{ vars.GCP_PROJECT_ID }}

    - name: Upload Binary to GCP
      run: |
        BINARY_NAME=$(git rev-parse --short HEAD)
        gsutil cp ./masa-node gs://${{ vars.GCP_BUCKET_NAME }}/${{ github.ref_name }}/$BINARY_NAME
        gsutil cp ./masa-node gs://${{ vars.GCP_BUCKET_NAME }}/${{ github.ref_name }}/masa-node
        gsutil cp  gs://${{ vars.GCP_BUCKET_NAME }}/${{ github.ref_name }}/masa-node
        gsutil cp ./contracts/* gs://${{ vars.GCP_BUCKET_NAME }}/${{ github.ref_name }}/


