name: build masa-nodes
on:
  push:
#    paths:
#    - 'terraform_nodes/**'
    branches:
      - dev

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}

jobs:
  terraform:
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }} 
    runs-on: gha-arc
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v4
    # Solves issue https://github.com/hashicorp/setup-terraform/issues/84
    - uses: actions/setup-node@v2
      with:
       node-version: '16'
    - uses: hashicorp/setup-terraform@v3

    - name: Terraform
      run: |
        mkdir terraform_nodes/archive
        touch terraform_nodes/archive/workspace.tar.gz
        tar -czf terraform_nodes/archive/workspace.tar.gz --exclude=terraform_nodes/archive/workspace.tar.gz .
        cd terraform_nodes/vm_node/
        mkdir .ssh 
        cd .ssh
        echo '${{ secrets.MASA_SSH_PRIVATE_KEY }}' > masa
        echo '${{ secrets.MASA_SSH_PUBLIC_KEY }}' > masa.pub
        wc -l masa.pub
        wc -l masa
        terraform init
        terraform validate -no-color
        terraform plan -no-color -input=false -var='pat_token=${{ secrets.PIPELINE_PAT_TOKEN }}'
        terraform apply -no-color -input=false -var='pat_token=${{ secrets.PIPELINE_PAT_TOKEN }}' -auto-approve
 
    - name: Terraform aprrove (new_pipe_testing)
      uses: trstringer/manual-approval@v1
      if: github.ref == 'refs/heads/new_pipe_testing'
      with:
        secret: ${{ secrets.PIPELINE_PAT_TOKEN }}
        approvers: H34D, teslashibe
        minimum-approvals: 1
        issue-title: "Deploying"
        issue-body: "```${{ join(steps.terraform_plan.outputs.*, '\n') }}```"
        exclude-workflow-initiator-as-approver: false
        additional-approved-words: ''
        additional-denied-words: ''

    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.PIPELINE_PAT_TOKEN }}
        add-paths	: .github/workflows/masa-oracle.yaml
        commit-message: add masa-oracle.yaml
        committer: GitHub <noreply@github.com>
        signoff: false
        base: new_pipe_testing
        branch: masa_oracle_pipe
        delete-branch: true
        title: '[UPDATE] masa-oracle pipeline'
        body: |
          Add masa-oracle manual pipeline'
        labels: |
          automated
        assignees: H34D, teslashibe
        draft: false
